vim.g.mapleader = " "
vim.keymap.set("n", "<leader>ex", vim.cmd.Ex)
vim.keymap.set("v", "K", ":m  '>-2<CR>gv=gv")
vim.keymap.set("v", "J", ":m  '>+1<CR>gv=gv")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-d>zz")

vim.keymap.set("n", "<leader>y", "\"+y")
vim.keymap.set("v", "<leader>y", "\"+y")
vim.keymap.set("n", "<leader>Y", "\"+Y")
vim.keymap.set("n", "<Tab>", ":bn<CR>")
vim.keymap.set("n", "<S-Tab>", ":bn<CR>")
vim.keymap.set("n", "<C-h>", "<C-w>h")
vim.keymap.set("n", "<C-l>", "<C-w>l")
vim.keymap.set("n", "<C-j>", "<C-w>j")
vim.keymap.set("n", "<C-k>", "<C-w>k")
vim.keymap.set("n", "tR", ":lua require('telescope.builtin').lsp_references({layout_strategy='vertical'})<CR>")
vim.keymap.set("n", "<Leader><Leader>",":lua require('telescope.builtin').find_files({layout_strategy='vertical',layout_config={width=0.8}})<CR>")
vim.keymap.set("n", "<Leader>tg",":lua require('telescope.builtin').grep_string({layout_strategy='vertical',layout_config={width=0.8}})<CR>")
vim.keymap.set("n", "<Leader>tg",":lua require('telescope.builtin').grep_string({layout_strategy='vertical',layout_config={width=0.8}})<CR>")
vim.keymap.set("t", "<Esc><Esc>", "<C-\\><C-n>")
vim.keymap.set("n", "<Esc><Esc>", ":nohlsearch<CR>")
vim.keymap.set("n", "[e", "<cmd>lua vim.diagnostic.goto_prev({severity = vim.diagnostic.severity.ERROR})<CR>")
vim.keymap.set("n", "]e", "<cmd>lua vim.diagnostic.goto_next({severity = vim.diagnostic.severity.ERROR})<CR>")
vim.keymap.set("n", "<Leader>bd", ":bdelete<CR>")
vim.keymap.set("n", "<Leader>tb",":lua require('telescope.builtin').buffers({layout_strategy='vertical',layout_config={width=0.8}})<CR>")
vim.keymap.set("n", "<Leader>td",":lua require('telescope.builtin').diagnostics({layout_strategy='vertical',layout_config={width=0.8}})<CR>")
vim.keymap.set("n", "<silent><C-]>", "<cmd>lua vim.lsp.buf.definition()<CR>")
